name: "Cronjob"
on:
  schedule:
    - cron: '15 */6 * * *'
  push:
    branches:
      - 'main'

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Remove .tmp folder (if it exists)
        run: |
          if [ -d .tmp ]; then
            rm -rf .tmp
          fi
      - name: Prepare
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir .tmp
      - name: Collect articles
        run: |
          git clone https://github.com/SergKorol/DevToArticlesList.git
          cd DevToArticlesList/DevToArticlesList
          dotnet restore
          dotnet run --project DevToArticlesList.csproj -- \
            --username=serhii_korol_ab7776c50dba \
            --template-file='./templates/articles.md.tpl' \
            --out-file='.tmp/articles.md.tpl' \
            --limit=5
      - name: Collect weathers
        run: |
          go install github.com/huantt/weather-forecast@latest
          weather-forecast update-weather --days=3 --city=Kyiv  --weather-api-key="${{ secrets.WEATHER_API_KEY }}" --template-file='templates/weathers.md.tpl' --out-file='.tmp/weathers.md.tpl'
      - name: Merge templates
        run: |
          go install github.com/huantt/merge-templates@v1.0.0
          merge-templates README.md 'templates/README.md.tpl' '.tmp/articles.md.tpl' '.tmp/weathers.md.tpl'
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if git diff --cached --exit-code; then
             echo "No changes to commit."
             exit 0
           else
             git commit -m "update"
             git rebase main
             git push origin main
           fi
