name: "Cronjob"
on:
  schedule:
    - cron: '15 */6 * * *'
  push:
    branches:
      - 'main'

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Remove .tmp folder (if it exists)
        run: |
          if [ -d .tmp ]; then
            rm -rf .tmp
          fi
          mkdir .tmp

      - name: Get latest artifact run id
        run: |
          ARTIFACT_RUN_ID=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=1" | jq '.artifacts[0].workflow_run.id')
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ca-fires-history-db
          path: ./data/
          run-id: ${{ env.artifact_run_id }} # Run ID of the artifact (SQLite DB) uploaded from the last run
          github-token: ${{ secrets.GH_PAT  }} # REQUIRED. See https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
          continue-on-error: true

      - name: Display downloaded file
        run: ls data/

      - name: Collect articles
        run: |
          git clone https://github.com/SergKorol/DevToArticlesList.git
          cd DevToArticlesList/DevToArticlesList
          dotnet restore
          dotnet run --project DevToArticlesList.csproj -- \
            --api-key="${{ secrets.DEV_TO_API_KEY }}" \
            --template-file='../../templates/articles.md.tpl' \
            --out-file='../../.tmp/articles.md.tpl' \
            --limit=5

      - name: Collect weathers
        run: |
          git clone https://github.com/SergKorol/ForecastWeather.git
          cd ForecastWeather/ForecastWeather
          dotnet restore
          dotnet run --project ForecastWeather.csproj -- \
            --days=3 \
            --city=Kyiv \
            --weather-api-key="${{ secrets.WEATHER_API_KEY }}" \
            --template-file='../../templates/weathers.md.tpl' \
            --out-file='../../.tmp/weathers.md.tpl'

      - name: Merge templates
        run: |
          git clone https://github.com/SergKorol/MergeTemplates.git
          cd MergeTemplates/MergeTemplates
          dotnet restore
          dotnet run --project MergeTemplates.csproj -- \
            ../../README.md \
            '../../templates/README.md.tpl' \
            '../../.tmp/articles.md.tpl' \
            '../../.tmp/weathers.md.tpl'

      - name: Post published articles to LinkedIn
        run: |
          git clone https://github.com/SergKorol/PostDevToLi.git
          cd PostDevToLi/PostDevToLi
          dotnet restore
          dotnet run --project PostDevToLi.csproj -- \
          --api-key="${{ secrets.DEV_TO_API_KEY }}" \
          --access-token="${{ secrets.ACCESS_TOKEN }}" \
          --ago=72
          cp posted_articles.db ../../templates/posted_articles.db

      - name: Upload SQLite database
        uses: actions/upload-artifact@v3
        with:
          name: sqlite-db
          path: ./data/posted_articles.db

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if git diff --cached --exit-code; then
             echo "No changes to commit."
             exit 0
           else
             git commit -m "update"
             git rebase main
             git push origin main
           fi
